server:
  port: 8082
spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
# TODO: Convert to reactive
#  r2dbc:
#    url: r2dbc:postgresql://localhost:15432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    pool:
#      enabled: false
#      initial-size: 100
#      max-size: 500
#      max-idle-time: 30m
#      validation-query: SELECT 1
#    data:
#      r2dbc:
#        repositories:
#          enabled: true

#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# swagger-ui custom path
springdoc:
  swagger-ui.path: /swagger-ui.html
  show-actuator: true

logging:
  level:
    org.springframework: ERROR
    org.anz.account: DEBUG

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true